console.log(">>> 1 bootstrap <<<");
import "./bootstrap";
console.log(">>> 2 http <<<");
import http from "http";
// console.log(">>> 3 graceful <<<");
// import gracefulShutdown from "http-graceful-shutdown";
console.log(">>> 4 database <<<");
import "./database";
console.log(">>> 5 app <<<");
import "./app";
console.log(">>> 6 socket <<<");
import "./libs/socket";
console.log(">>> 7 logger <<<");
import logger from "./utils/logger";
console.log(">>> 8 whatsappMonitor <<<");
import "./monitoring/whatsappMonitor";
console.log(">>> 9 backendQueues <<<");
import "./backendQueues";
console.log(">>> 10 backendCronJobs <<<");
import "./backendCronJobs";
console.log(">>> 11 StartAllWA <<<");
import "./services/WbotServices/StartAllWhatsAppsSessions";
console.log(">>> 12 Company <<<");
import "./models/Company";
console.log(">>> ALL OK <<<");
process.exit(0);
